<a href="https://colab.research.google.com/github/dioz-s/StudyGroup4/blob/main/Tugas_Datik_Dios_Suryanaipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import kagglehub
import pandas as pd
import os

path = kagglehub.dataset_download("codebynadiia/gdp-per-country-20152025")

print("Dataset tersimpan di:", path)

print(os.listdir(path))

Using Colab cache for faster access to the 'gdp-per-country-20152025' dataset.
Dataset tersimpan di: /kaggle/input/gdp-per-country-20152025
['2015-2025.csv']

In [18]:
# Install dependensi

import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "2015-2025.csv"

# muat versi akhirnya
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "codebynadiia/gdp-per-country-20152025",
  file_path,

)

print("First 5 records:", df.head())

/tmp/ipykernel_676/2240033115.py:9: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'gdp-per-country-20152025' dataset.
First 5 records:        Country      2015      2016      2017      2018      2019    2020  \
0  Afghanistan   20057.0   18020.0   18883.0   18336.0   18876.0   20136
1      Albania   11525.0   12003.0   13209.0   15337.0   15582.0   15271
2      Algeria  187494.0  180764.0  190004.0  194507.0  193361.0  164774
3      Andorra    2789.0    2895.0    2993.0    3217.0    3155.0    2885
4       Angola  131661.0  114764.0  139835.0  114189.0   94671.0   66521

       2021      2022      2023      2024      2025
0   14278.0   14501.0   17248.0       NaN       NaN
1   18086.0   19185.0   23388.0   27259.0   28372.0
2  185850.0  225709.0  247789.0  264913.0  268885.0
3    3325.0    3376.0    3786.0    4038.0    4035.0
4   84375.0  142442.0  109764.0  115946.0  113343.0

In [19]:
file_path = os.path.join(path, "2015-2025.csv")

df = pd.read_csv(file_path)

print(df.head())
print(df.columns)

       Country      2015      2016      2017      2018      2019    2020  \
0  Afghanistan   20057.0   18020.0   18883.0   18336.0   18876.0   20136
1      Albania   11525.0   12003.0   13209.0   15337.0   15582.0   15271
2      Algeria  187494.0  180764.0  190004.0  194507.0  193361.0  164774
3      Andorra    2789.0    2895.0    2993.0    3217.0    3155.0    2885
4       Angola  131661.0  114764.0  139835.0  114189.0   94671.0   66521

       2021      2022      2023      2024      2025
0   14278.0   14501.0   17248.0       NaN       NaN
1   18086.0   19185.0   23388.0   27259.0   28372.0
2  185850.0  225709.0  247789.0  264913.0  268885.0
3    3325.0    3376.0    3786.0    4038.0    4035.0
4   84375.0  142442.0  109764.0  115946.0  113343.0
Index(['Country', '2015', '2016', '2017', '2018', '2019', '2020', '2021',
       '2022', '2023', '2024', '2025'],
      dtype='object')

In [20]:
#Cleaning datanya

print("Jumlah baris dan kolom:", df.shape)
print("\nNama kolom:")
print(df.columns.tolist())

# Hapus spasi pada nama negara
df["Country"] = df["Country"].str.strip()
years = [str(year) for year in range(2015, 2025)]

for year in years:
    df[year] = pd.to_numeric(df[year], errors="coerce")

# Cek missing value
print("\nMissing value:")
print(df[["Country"] + years].isnull().sum())

# Hapus nama negara yg kosoong dan duplikat

df = df.dropna(subset=["Country"])
df = df.drop_duplicates(subset=["Country"])

print("\nUkuran data setelah cleaning:", df.shape)

Jumlah baris dan kolom: (196, 12)

Nama kolom:
['Country', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']

Missing value:
Country    0
2015       1
2016       1
2017       1
2018       1
2019       1
2020       0
2021       2
2022       2
2023       2
2024       4
dtype: int64

Ukuran data setelah cleaning: (196, 12)

In [21]:
#saya pilih 5 negara
countries = [
    "United States",
    "China",
    "India",
    "Japan",
    "Germany"
]

df_selected = df[df["Country"].isin(countries)].copy()

df_selected[["Country", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024"]]

,Country,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
36,China,11307226.0,11448003.0,12503299.0,14110963.0,14572410.0,15103357,18190803.0,18307816.0,18270351.0,18748009.0
63,Germany,3423915.0,3536808.0,3761764.0,4053846.0,3957645.0,3936989,4351188.0,4166872.0,4527009.0,4658526.0
76,India,2103588.0,2294797.0,2651474.0,2702930.0,2835606.0,2674852,3167271.0,3346107.0,3638490.0,3909097.0
85,Japan,4444931.0,5003678.0,4930837.0,5040881.0,5117995.0,5054069,5039148.0,4262146.0,4213167.0,4026211.0
187,United States,18295000.0,18804900.0,19612100.0,20656525.0,21539975.0,21354125,23681175.0,26006900.0,27720725.0,29184900.0

In [22]:
#ngubah formatnya agar kebawah
years = [str(year) for year in range(2015, 2025)]

df_long = df_selected.melt(
    id_vars="Country",
    value_vars=years,
    var_name="Year",
    value_name="GDP"
)

df_long["Year"] = df_long["Year"].astype(int)

df_long.head(10)

         Country  Year         GDP
0          China  2015  11307226.0
1        Germany  2015   3423915.0
2          India  2015   2103588.0
3          Japan  2015   4444931.0
4  United States  2015  18295000.0
5          China  2016  11448003.0
6        Germany  2016   3536808.0
7          India  2016   2294797.0
8          Japan  2016   5003678.0
9  United States  2016  18804900.0

In [23]:
df_race = df_long.pivot(
    index="Year",
    columns="Country",
    values="GDP"
)

df_race

Country       China    Germany      India      Japan  United States
Year
2015     11307226.0  3423915.0  2103588.0  4444931.0     18295000.0
2016     11448003.0  3536808.0  2294797.0  5003678.0     18804900.0
2017     12503299.0  3761764.0  2651474.0  4930837.0     19612100.0
2018     14110963.0  4053846.0  2702930.0  5040881.0     20656525.0
2019     14572410.0  3957645.0  2835606.0  5117995.0     21539975.0
2020     15103357.0  3936989.0  2674852.0  5054069.0     21354125.0
2021     18190803.0  4351188.0  3167271.0  5039148.0     23681175.0
2022     18307816.0  4166872.0  3346107.0  4262146.0     26006900.0
2023     18270351.0  4527009.0  3638490.0  4213167.0     27720725.0
2024     18748009.0  4658526.0  3909097.0  4026211.0     29184900.0

In [24]:
#instal race bar chartnya
!pip install bar_chart_race

Requirement already satisfied: bar_chart_race in /usr/local/lib/python3.13/dist-packages (0.1.0)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.13/dist-packages (from bar_chart_race) (2.2.3)
Requirement already satisfied: matplotlib>=3.1 in /usr/local/lib/python3.13/dist-packages (from bar_chart_race) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1->bar_chart_race) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1->bar_chart_race) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1->bar_chart_race) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1->bar_chart_race) (1.5.1)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1->bar_chart_race) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1->bar_chart_race) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1->bar_chart_race) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1->bar_chart_race) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1->bar_chart_race) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=0.24->bar_chart_race) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=0.24->bar_chart_race) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib>=3.1->bar_chart_race) (1.17.0)

In [25]:
import bar_chart_race as bcr

bcr.bar_chart_race(
    df=df_race,
    filename="gdp_race_5_countries.mp4",
    orientation="h",
    sort="desc",
    n_bars=5,
    fixed_order=False,
    fixed_max=True,
    steps_per_period=30,
    period_length=1200,
    interpolate_period=True,
    label_bars=True,
    bar_size=0.8,
    period_label={
        "x": 0.95,
        "y": 0.15,
        "ha": "right",
        "va": "center",
        "size": 24
    },
    title="GDP Race: Top 5 Economies",
    figsize=(10, 6),
    dpi=144
)

/usr/local/lib/python3.13/dist-packages/bar_chart_race/_make_chart.py:286: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.
  ax.set_yticklabels(self.df_values.columns)
/usr/local/lib/python3.13/dist-packages/bar_chart_race/_make_chart.py:287: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.
  ax.set_xticklabels([max_val] * len(ax.get_xticks()))

In [26]:
from IPython.display import Video

Video("gdp_race_5_countries.mp4", embed=True)

In [27]:
from google.colab import files

files.download("gdp_race_5_countries.mp4")